defaults: &defaults
  m_api_url: 'http://moonwalk.cc'
  m_api_key: 'e551fd5050b620d61ceb48c658295b28'
  myshows_api_url: 'http://api.myshows.ru'
  trakt_api_url: 'https://api-v2launch.trakt.tv'
  trakt_api_key: '3ebc98989a011e8ac9c79609f5d5b7ba5378c9a917be15e399ff2aa28552f12d'
  trakt_api_secret: '83be15e8adc54e4e382e1b4535e427e2889f097dd30095ef0edeea234d87f8b4'
  yandex_api_url: 'https://cloud-api.yandex.net:443'
  yandex_api_key: 'fbdfc29b8a5f4668b2e6f0de49202ec3'
  kinopoisk_api_url: 'http://rating.kinopoisk.ru'
  tvdb_api_key: '5B757353E14FA17B'
  tvdb_api_url: 'http://thetvdb.com'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults